# Generated by Django 2.2.24 on 2021-08-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(max_length=50)),
                ('collection_title', models.CharField(max_length=1024)),
                ('action', models.CharField(choices=[('added', 'added'), ('updated', 'updated'), ('removed', 'removed')], max_length=8)),
                ('datetime', models.DateField()),
            ],
        ),
    ]
