stages:
  - test

test:
  stage: test
  image: python:3.7
  before_script:
    - pip install -r $CI_PROJECT_DIR/requirements.txt
    - pip install -e $CI_PROJECT_DIR
    - python -c "import secrets; print(f'SECRET_KEY = \"{secrets.token_hex(16)}\"')" > $CI_PROJECT_DIR/ceda_opensearch/settings_local.py
  script:
    - python manage.py test django_opensearch.tests events.tests
